### PR TITLE
chore: generate new lockfile with updated npm to use lockfile v2

### PR DESCRIPTION
**Pull request by astone123**
It looks like the package-lock file was generated with an old version of npm that is using lockfile version 1. This is kind of annoying because GH actions gives an error when we try to install deps. We should use the newer versions of npm to manage packages. I'm running `8.19.2`

### CODE REVIEW

**Comment by wweitzel** [comment]
@astone123 I just installed version 8.19.2. Then I pulled this branch and ran `npm install` and it produced a different lock file than the one from this. Shouldn't it be the same?

**Comment by astone123** [comment]
Oh yeah I think it might be Node version not NPM version. Try latest Node v19

**Comment by wweitzel** [comment]
Installed node v19.

Now if I run npm install **on master** it makes a package.lock identical to yours. But if I run npm install **with this PR branch checked out** it makes a different one.

Weird.

**Review by wweitzel — APPROVED** [review]
Gonna merge this

**Comment by wweitzel** [comment]
Merged this and then merge #7 with my update. Wonder whats gonna happen next time you run `npm install` now haha.

**Pull request merged**
