### PR TITLE
chore: run build and test on master to normalize workflows

### PR DESCRIPTION
**Pull request by astone123**
Right now we have two workflows:
- Build and Test
- Deploy

The Deploy workflow does some stuff that we already do in Build and Test. This PR makes it so that all of the jobs are in one workflow, and `deploy` only runs after building and testing are successful, and only if the branch is `master`, otherwise we skip the deploy step

This way we're doing the same build and test on `master` that we are in PRs. Less duplication

### CODE REVIEW

**Comment by wweitzel** [comment]
@astone123 Do we need to add a
```
- uses: actions/download-artifact@v3
        with:
          name: build
```

to the deploy workflow? It needs that folder for the `Sync files to S3` step

**Comment by astone123** [comment]
I think it's easier to do it like this with them all in one workflow. Then you get a nice diagram of the flow
Screenshot 2023-10-22 at 6 09 49 PM

Github actions doesn't really have a built-in way to upload and download artifacts across different workflows as far as I can tell

**Comment by astone123** [comment]
I think re-naming the workflow improves the PR check view

Screenshot 2023-10-22 at 6 49 25 PM

**Review by wweitzel — APPROVED** [review]
LGTM

**Pull request merged**
